name: Build and Release

on:
  workflow_dispatch:   # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore JadeDbClient

    - name: Build
      run: dotnet build --configuration Release --no-restore JadeDbClient

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal JadeDbClient

    - name: Pack code for GitHub Packages
      run: dotnet pack --configuration Release -o ./nupkg JadeDbClient

    - name: Publish to GitHub Packages (PAT)
      run: dotnet nuget push ./nupkg/*.nupkg \
           -s https://nuget.pkg.github.com/KaustavCodes/index.json \
           -k ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg \
           -k ${{ secrets.NUGET_API_KEY }} \
           -s https://api.nuget.org/v3/index.json
