name: Build and Release

on:
  workflow_dispatch:   # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore JadeDbClient

      - name: Build
        run: dotnet build JadeDbClient --configuration Release --no-restore

      - name: Run tests
        run: dotnet test JadeDbClient --no-restore --verbosity normal

      - name: Pack NuGet package
        run: dotnet pack JadeDbClient --configuration Release --no-build -o ./nupkg

      - name: Publish to GitHub Packages (PAT)
        run: dotnet nuget push ./nupkg/*.nupkg -s https://nuget.pkg.github.com/KaustavCodes/index.json -k ${{ secrets.MY_GITHUB_TOKEN }} --skip-duplicate

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
